### ISSUE TITLE
[Bug]: Chipped requires CTM on server-side

### ISSUE THREAD

**Issue by pavog** [CookieCNetwork/Chipped#186] opened 2023-03-13 14:48 UTC
### Bug Description

Hi, I installed [chipped-fabric-1.19.2-2.1.2.jar](https://www.curseforge.com/minecraft/mc-mods/chipped/files/4434884) on a fresh new Fabric 1.19.2 (0.14.17) server.
I also installed [[Fabric] Resourceful lib 1.1.23](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib/files/4434137) and [[1.19.2] Fabric API 0.75.1+1.19.2](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4409837).

Now when I want to start the server, I get the error message telling me to install CTM ([ConnectedTexturesMod](https://www.curseforge.com/minecraft/mc-mods/ctm)) or its fabric equivalent ([CTM refabricated](https://www.curseforge.com/minecraft/mc-mods/ctm-refabricated)).

I wonder why I need to install the client-only mod CTM on my server?

<details>
  <summary>Error message</summary>

```
[main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install ctm, any version.
Unmet dependency listing:
	 - Mod 'Chipped' (chipped) 2.1.2 requires any version of ctm, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:14[8](https://aternos.org/log/#L8)) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:6[9](https://aternos.org/log/#L9)) [fabric-loader-0.[14](https://aternos.org/log/#L14).[17](https://aternos.org/log/#L17).jar:?]
```
</details>

Full server log: https://mclo.gs/bQ8Vmhi

### How to Reproduce?

1. Install a new Fabric server using Fabric 1.19.2 (0.14.17)
2. Install [chipped-fabric-1.19.2-2.1.2.jar](https://www.curseforge.com/minecraft/mc-mods/chipped/files/4434884) 
3. Installed [[Fabric] Resourceful lib 1.1.23](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib/files/4434137)
4. Install [[1.19.2] Fabric API 0.75.1+1.19.2](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4409837)
5. Start the server

### Expected Behavior

Should run without any problems and not crash the server

### Version

fabric 1.19.2 2.1.2

### Mod Loader Version

0.14.17

### Mod Loader

Fabric

### Logs or additional context

https://mclo.gs/bQ8Vmhi

**Comment by AlexNijjar** [comment] 2023-03-13 14:53
duplicate of #172

**Closed as not planned by AlexNijjar** 2023-03-13 14:53 UTC
Labels: bug, duplicate
