### ISSUE TITLE
[Bug]: 1.20.1 - Sophisticated Backpack crashes after updating Chipped above V3.0.1

### ISSUE THREAD

**Issue by Wxam** [CookieCNetwork/Chipped#273] opened 2024-02-04 17:19 UTC
### Bug Description

Whenever I update Chipped above Version 3.0.1 Sophisticated Backpacks crashes the game.
If I downgrade to Version 3.0.1 again everything works fine again.

Seems like the new update became incompatible with Sophisticated Backpacks

### How to Reproduce?

Download Sophisticated Backpacks
Download Chipped (newest version) 
-> End up crashing
Downgrade Chipped to version 3.0.1
-> Everything works fine

### Version

3.0.4

### Mod Loader Version

1.20.1 - 47.2.20

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Sazuzaki** [comment] 2024-02-04 17:20
Can confirm, happens with me too. Thanks for providing a version that doesn't crash.

**Comment by CodexAdrian** [comment] 2024-02-04 18:42
Duplicate of #269

**Closed as completed by CodexAdrian** 2024-02-04 18:42 UTC
Labels: bug
