### ISSUE TITLE
Fabric version prevents entering worlds

### ISSUE THREAD

**Issue by UnusedCactus** [CookieCNetwork/Chipped#86] opened 2021-11-28 20:27 UTC
The Fabric version of Chipped prevents the loading of worlds on the latest Fabric loader (0.12.5-1.17.1) Worlds attempted to be loaded appear to load and will fully finish loading, however say that you were disconnected from the server upon finishing loading. The only thing that can be done at this point is exiting to the server menu. This occurs upon loading any world, including newly created worlds. I do not believe this is caused by any other mods.

**Comment by Minionade** [comment] 2021-12-04 17:19
I haven't had this issue, can you try creating an instance with just chipped and attempt to replicate it?  if it does not persist, you may have to play around and figure out if there's a conflict making it happen.  I know I was unable to launch the game with both Chipped and Consistency+ installed, but I'm not sure if that's relevant to your issue.

**Comment by Minionade** [comment] 2021-12-04 17:20
Also, issue reports like this aren't much help if you don't include your crash log, mods installed (version included), etc.

**Comment by UnusedCactus** [comment] 2021-12-05 16:09
Alright. Will do.

**Comment by UnusedCactus** [comment] 2021-12-05 16:17
Seems you were right. Some mod (Probably Consistency+ in combination with Chipped) made this issue. The issue should probably be fixed either way, as no other mod has reacted like this for me.
![2021-12-05_11 12 22](https://user-images.githubusercontent.com/87100678/144754376-b625bd02-fa6b-4cac-afa7-61d1988523a8.png)
 ^an image of the mod working correctly, in my case

**Comment by Minionade** [comment] 2021-12-06 01:40
The incompatibility isn't with Chipped and Consistency+, at least not with the following versions:
Fabric 0.12.8
Architectury API 2.6.35
Chipped 1.1.1
Consistency+ 0.4.2
Fabric API 0.44.0
![Untitled](https://user-images.githubusercontent.com/95131293/144773933-bab2a097-1337-456d-9c02-80714c3a785c.png)

You'll have to keep looking around, hope you find the issue.

**Comment by MsRandom** [comment] 2021-12-10 12:41
Duplicate of #85 and #69

**Closed as completed by MsRandom** 2021-12-10 12:41 UTC
