### ISSUE TITLE
[Bug]:  Chipped and Every Wood Compat incompat looping

### ISSUE THREAD

**Issue by Mysticpasta1** [CookieCNetwork/Chipped#214] opened 2023-07-07 06:33 UTC
### Bug Description

https://www.curseforge.com/minecraft/mc-mods/chipped/files/4558849 is incompatible with https://www.curseforge.com/minecraft/mc-mods/every-compat/files/4616032 with can't fit X number into 3 (packet compression issue), this is caused only when a client with the same mods connect to either a dedicated server with them or to another players world using essentials. Nothing fixes the error, I think it is due to every wood compat load block vars from chipped then chipped loading those new block vars from every wood compat making new vars for it and so on in a loop. Tried to also disable this in the configs for every wood compat, doesn't fix the issue.

### How to Reproduce?

Add chipped and every wood compat into a dedicated server and a client
load client to server
disconnect due to block vars looping and causing X number can't fit into 3

### Expected Behavior

chipped shouldn't load extra variants for new block variants of every wood compat on client loading into world on a dedicated server

### Version

2.1.5

### Mod Loader Version

1.19.2-43.2.14

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment] 2023-07-07 07:00
Duplicate of #195

**Closed as not planned by AlexNijjar** 2023-07-07 07:00 UTC
Labels: bug
