### ISSUE TITLE
Chipped Workbenches do not display items correctly

### ISSUE THREAD

**Issue by AzureMonument** [CookieCNetwork/Chipped#72] opened 2021-08-21 14:40 UTC
In the chipped workbenches the displays are not even remotely in order- and the result you get by selecting a certain tile is often completely different than the tile itself, as displayed below.
This happens in every workbench I've tested to some degree (I have all but the alchemy one in survival)

![Screenshot 2021-08-21 103911](https://user-images.githubusercontent.com/43318292/130325330-04bd8dc4-9c59-4087-8f85-4e244beeb516.png)

![Screenshot 2021-08-21 103838](https://user-images.githubusercontent.com/43318292/130325310-f9a04069-4af3-4faa-a1ec-e5834fe965e2.png)

**Comment by largeorbitalobject** [comment] 2021-08-21 22:19
Hello, I can confirm this is occurring for Forge as well. On Forge 36.2.0.

**Comment by ghost** [comment] 2021-08-28 16:55
Fabric too, but only on serverside

**Comment by BioOnPC** [comment] 2021-08-28 23:32
From some experimentation, it seems like this issue occurs because the list of output blocks is sequentially ordered by the item ID's number, but list of block options is ordered manually. Clicking on any of the options with advanced tooltips on brings up the output block that you would expect based on the number at the end of the ID.

**Comment by notmaroun** [comment] 2021-08-31 20:49
I'm having this issue too with chipped on my server.

**Comment by Sixdd6** [comment] 2021-10-25 18:45
Getting this too on dedicated server, takes ages to figure out which ones to click to get the right block.
Forge: 36.2.4
Chipped: 1.1.2

**Comment by Kekie6** [comment] 2021-11-16 09:22
To summerize, this issue occurs on both forge and fabric, but only on servers (can confirm after testing on both forge and fabric).
The issue is caused because output blocks are ordered sequentially by their item ID's, while block options inside the workbench are ordered manually.

**Comment by Kekie6** [comment] 2021-12-10 12:29
Should be fixed in the next patch

**Closed as completed by Kekie6** 2021-12-10 12:29 UTC
Labels: bug, fabric, forge
