### ISSUE TITLE
[Bug]: BOTANIST_WORKBENCH_TYPE results in java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by wolfieboy09** [CookieCNetwork/Chipped#271] opened 2024-02-03 15:52 UTC
### Bug Description

![image](https://github.com/terrarium-earth/Chipped/assets/105564186/94d0279b-969a-4c43-9683-5975c9ff86f2)

The game crashes

### How to Reproduce?

1. Install the latest version
2. Load the mod

### Expected Behavior

For it to not crash

### Version

3.0.4

### Mod Loader Version

1.20.1 - 47.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment] 2024-02-04 02:06
duplicate of #269

**Closed as not planned by AlexNijjar** 2024-02-04 02:06 UTC
Labels: bug
