### ISSUE TITLE
Chipped

### ISSUE THREAD

**Issue by tb614** [CookieCNetwork/Chipped#130] opened 2022-05-23 02:00 UTC
Should add in auto chipping tables, for doing mass amounts of blocks it is too cumbersome to mess with the tables, thanks.

**Comment by SevenChords** [comment] 2022-08-19 23:05
This would be especially useful for bigger building projects where you want to use thousands of chipped blocks, manually crafting them all is way too much effort and usually results in chipped blocks only getting used for "smaller" projects (at least on the server i am playing on right now that does happen to use the chipped mod as well)

**Comment by jamuspsi** [comment] 2023-05-16 05:38
This is VERY essential.  An awful lot of modern minecraft play happens in modpacks with various automation piping options, and the resources to build LARGE.  Especially now that the number of options for each block have increased, it's INCREDIBLY tedious to scroll and find the one you need a hundred stacks of.  I'll cheat with /setemc but this really needs some attention, if only as a companion dependency.  I wish I was confident enough to make it myself.

**Comment by AlexNijjar** [comment] 2023-10-26 08:02
Gonna mark this as a duplicate of (#205) because that one has an actual title and a temporary workaround.

**Closed as not planned by AlexNijjar** 2023-10-26 08:02 UTC
Labels: duplicate, enhancement
