### ISSUE TITLE
[Bug]: Smooth Lighting isn't applied to blocks with connected textures

### ISSUE THREAD

**Issue by Swedz** [CookieCNetwork/Chipped#231] opened 2023-08-26 22:46 UTC
### Bug Description

Blocks in Chipped that use connected textures do not render with smooth lighting on them as expected. In the screenshot below, you can see that the Thick Inlayed Quartz from Chipped is rendering with very blocky lighting (as if smooth lighting was off) where the Smooth Quartz (and other blocks around it) from vanilla Minecraft renders with smooth lighting correctly.
![2023-08-26_18 03 48](https://github.com/terrarium-earth/Chipped/assets/6707125/cef31bb0-d377-4664-8466-b2d499cb3be1)

I ran this test on an installation that only had Chipped, Athena, and Resourceful Lib installed (as those are required for Chipped to run).

### How to Reproduce?

1. Place connected texture blocks such as Thick Inlayed Quartz in a dark area
2. Place a light source

### Expected Behavior

Smooth lighting would be applied to the blocks as it is with normal blocks

### Version

3.0.1

### Mod Loader Version

1.20.1 - 47.1.44

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Treeways** [comment] 2023-09-14 17:08
Can't reproduce on Chipped 1.20.1-3.0.1 with Quilt 0.20.2.

![image](https://github.com/terrarium-earth/Chipped/assets/56928485/491beeff-2b0c-4581-8abf-70e10baccaa9)

**Comment by stapes1111** [comment] 2023-09-22 00:32
issue is present in 1.19.2 Chipped Forge.

**Comment by stapes1111** [comment] 2023-09-22 00:33
![image](https://github.com/terrarium-earth/Chipped/assets/145729042/e6428cb3-f6dd-4134-84d0-d8cd9b7f173e)

**Comment by ThatGravyBoat** [comment] 2023-09-22 00:47
seeing as 1.20 and 1.19 use completely different rendering this is likely an issue with just how forge smooth lighting works on custom models

**Comment by ThatGravyBoat** [comment] 2023-09-30 13:44
This was fixed in 1.20 in the latest athena, 1.19 used a different system I cant fix that

**Closed as completed by ThatGravyBoat** 2023-09-30 13:44 UTC
Labels: bug
