### ISSUE TITLE
[Bug]: NULL error with BOTANIST_WORKBENCH (NoSuchFieldError)

### ISSUE THREAD

**Issue by wolfieboy09** [CookieCNetwork/Chipped#274] opened 2024-02-04 18:36 UTC
### Bug Description

In the logs, BOTANIST_WORKBENCH has a `null` error.

### How to Reproduce?

1. Download any chipped version
2. It may crash

### Expected Behavior

For it to not crash

### Version

ALL VERSION DO THIS

### Mod Loader Version

1.20.1 - 47.2.0

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/iBYS2ygG

### Code of Conduct

- [x] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment] 2024-02-04 18:42
Duplicate of #269

**Closed as completed by CodexAdrian** 2024-02-04 18:42 UTC
Labels: bug
