### ISSUE TITLE
[Bug]: CRASH

### ISSUE THREAD

**Issue by d-rick** [CookieCNetwork/Chipped#270] opened 2024-02-03 14:25 UTC
### Bug Description

en mi juego con muchos mas mods, al actualizar el mod a las versiones salidas en 2024, no inicia el juego y me da un error: Caused by: java.lang.NoSuchFieldError: BOTANIST_WORKBENCH_TYPE

Es posible que sea alguna incompatibilidad con quark o algún otro mod.

### Version

3.0.4

### Mod Loader Version

1.20.1 - 47.2.0

### Mod Loader

Forge

### Logs or additional context

[crash-2024-02-03_09.07.58-client.txt](https://github.com/terrarium-earth/Chipped/files/14151747/crash-2024-02-03_09.07.58-client.txt)

[latest.log](https://github.com/terrarium-earth/Chipped/files/14151751/latest.log)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment] 2024-02-04 02:06
duplicate of #269

**Closed as not planned by AlexNijjar** 2024-02-04 02:06 UTC
Labels: bug
