### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pooguylmao** [CookieCNetwork/Chipped#192] opened 2023-03-24 22:37 UTC
### Bug Description

Many planks (for example: Oak Planks Pannel) appear as the normal texture
the ones which appear as normal texture sound really usefull for certain details

### How to Reproduce?

1. craft any one of these in survival: Planks Panel, Cornered Planks, Crated Planks, Encolsed Planks, Framed Planks, Natural Planks, Pegged Planks, Smooth Planks, Whirlwind Planks
2. if in creative go to mod tab and search "Plank" and look at the planks listen above
3. Notice texture beeing default

### Expected Behavior

Although this bug is not gamebreaking it is pretty inconvenient, as the textures don't show, there's not much to explain

### Version

1.1.21

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment] 2023-07-05 10:39
Duplicate of #206

**Closed as not planned by AlexNijjar** 2023-07-05 10:39 UTC
Labels: bug
